# JWT Configuration
jwt:
  secret: 2?Q:mba;7mvN[^0=Ixw54z@YOiySC!TqGF)-20tOL`*qs^AlK_|gYoS;ah0r2Oj
  expiration: 1800_000 # 30 minutes
  issuer: 'Pozag Technology Solutions'
  audience: checkApp
  prefix: 'Bearer '
  excluded.urls: > 
    /users/login,
    /users/reset,
    /users/signup,
    /users/reset/*,
    /users/reset/**,
    /test/**,
    /error,
    /profile,
    /profile/*,
    /profile/**,
    /task,
    /task/*,
    /task/**,
    /users/profile/*,
    /users/profile/**,
    /users/userprofile/**,
    /users/userprofile/*,
    /dateevents/**,
    /dateevents/*,
    /forgot-password,
    /profilephoto/**,
    /profilephoto/profile/update/**,
    /profilephoto/updateProfilePhoto/**,
    /chat.sendMessage,
    /ws,
    /groupdates/**,
    /groupdates/*,
    /groupdates/usergroupdates/**,
    /groupdates/usergroupdates/*,
    /gdateinterests/*,
    /gdateinterests,
    /gdateinterests/**,
    /gmessages/*,
    /gmessages/**,
    /gmessages,



# Client Configuration  http://localhost:4200 https://1stdate.net
client:
  url: http://localhost:8100
  email:
    verify: 
      param: users/verifyEmail
      expiration: 86_400_000 # 24 hours
    reset: 
      param: users/resetPassword
      expiration: 1000_000 # 10 minutes  
    actualdate:
      param: users/actualDateEmail
      
